apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql
data:
  init.sh: |
    #!/bin/bash
    mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
      CREATE DATABASE IF NOT EXISTS \`$MYSQL_DATABASE\`;
      GRANT ALL PRIVILEGES ON \`$MYSQL_DATABASE\`.* TO '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
      FLUSH PRIVILEGES;
    EOSQL