apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_USER: "dXNlcg=="
  MYSQL_ROOT_PASSWORD: "UEFTU1dPUkQ="
  MYSQL_PASSWORD: "UEFTU1dPUkQ="
  MYSQL_DATABASE: "bXlfZGI="
  
